### ISSUE TITLE
NameError: name 'print_to_console' is not defined

### ISSUE THREAD

**Issue by tin2tin** [Jishnu-jithu/text-editor-addons#2]
\text-editor-addons-main\__init__.py", line 419, in register
    print_to_console.update_print(prefs, context)
    ^^^^^^^^^^^^^^^^
NameError: name 'print_to_console' is not defined

**Comment by Jishnu-jithu** [comment]
Thanks for pointing out that, i forgot to remove it from the code.

I have now removed the unused code from the __init__.py file.

**Comment by tin2tin** [comment]
Cool. It's working. Thank you.
